services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: unless-stopped
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - rabbitmq_go_net

  postgres:
    image: postgres:16.1
    restart: unless-stopped
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=passwd
      - POSTGRES_DB=property-db
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  data_parser:
    restart: unless-stopped
    container_name: data_parser
    build: 
      context: ./data_parser
      dockerfile: Dockerfile_data_parser
    volumes:
      - ./scraping_source:/data_parser/data
      - ./protobufs:/data_parser/protobufs
      - ./data_parser:/data_parser
    depends_on:
      - rabbitmq
      - postgres

networks:
  rabbitmq_go_net:
    driver: bridge
